name: Smurf-Future
favicon: null
layout_spectrum: 0.1772461065556854
typography_spectrum: 0.021425723796710372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5181250399909914
  lightness: 0.4698934678453952
  saturation: 0.24618240701965988
  rhythmicContrast: 0.39623703877441585
purpose: []
