name: Smurf-Future
favicon: null
layout_spectrum: 0.94222
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b70000'
    - '#fcfafb'
    - '#dda3ac'
    - '#c23940'
    - '#d07c85'
  brandStrength: 0.75
  lightness: 0.4698934678453952
  saturation: 0.24618240701965988
  rhythmicContrast: 0.39623703877441585
purpose: []
